### ISSUE TITLE
Cannot call setup.py without remoteobjects already installed

### ISSUE THREAD

**Issue by kewisch** [mozilla/bztools#6]
setup.py shouldn't depend on remoteobjects already being installed, but instead allow installing dependencies.
```
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    version=__import__('bugzilla').__version__,
  File "/Users/kewisch/mozilla/github/bztools/bugzilla/__init__.py", line 4, in <module>
    from remoteobjects import http
ImportError: No module named remoteobjects
```

**Comment by kewisch** [comment]
Actually, scratch that. I should have just ran `pip install -r requirements.txt`.
